name: Publish DotNetAppBase.Std.Library

on:
  workflow_dispatch:
  push:
    tags:
      - "DotNetAppBase.Std.Library-v*"

permissions:
  contents: read
  packages: write

jobs:
  publish_github_packages:
    uses: ./.github/workflows/publish-dotnet-package.yml
    with:
      project_path: src/DotNetAppBase.Std.Library/DotNetAppBase.Std.Library.csproj
    secrets: inherit

  publish_nugetorg:
    uses: ./.github/workflows/publish-nugetorg-package.yml
    with:
      project_path: src/DotNetAppBase.Std.Library/DotNetAppBase.Std.Library.csproj
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
